import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatMoney } from "./format";

export type PdfTx = {
  date: string;
  type: "in" | "out" | "credit" | "debit";
  category: string;
  payment_method: string;
  note: string | null;
  amount: number;
};

export type PdfCustomer = {
  name: string;
  phone: string | null;
  email: string | null;
};

const BRAND_BLUE: [number, number, number] = [30, 58, 138]; // navy
const ACCENT_BLUE: [number, number, number] = [59, 130, 246];
const GREEN: [number, number, number] = [22, 163, 74];
const RED: [number, number, number] = [220, 38, 38];

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
}

function header(doc: jsPDF, businessName: string, title: string) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(...BRAND_BLUE);
  doc.rect(0, 0, w, 70, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(businessName.toUpperCase(), 24, 34);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(220, 230, 255);
  doc.text("Financial Management System", 24, 50);

  // Pill button on the right
  doc.setFillColor(...ACCENT_BLUE);
  doc.roundedRect(w - 150, 22, 120, 26, 13, 13, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(title.toUpperCase(), w - 90, 38, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(220, 230, 255);
  doc.text(new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }), w - 30, 62, {
    align: "right",
  });
}

function footer(doc: jsPDF, businessName: string) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...BRAND_BLUE);
  doc.rect(0, h - 28, w, 28, "F");
  doc.setTextColor(220, 230, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(`Generated by ${businessName.toUpperCase()}`, w / 2, h - 11, { align: "center" });
}

export function generateCustomerStatement(opts: {
  businessName: string;
  customer: PdfCustomer;
  transactions: PdfTx[];
}) {
  const { businessName, customer, transactions } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  header(doc, businessName, "Statement");

  const w = doc.internal.pageSize.getWidth();

  // Customer details + balance card
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(24, 90, w - 48, 80, 8, 8, "F");

  doc.setTextColor(120, 130, 145);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("CUSTOMER DETAILS", 40, 110);

  doc.setTextColor(20, 25, 40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(customer.name, 40, 130);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90, 100, 115);
  const contact = [customer.phone && `Phone: ${customer.phone}`, customer.email && `Email: ${customer.email}`]
    .filter(Boolean)
    .join("   |   ");
  doc.text(contact || "—", 40, 148);

  // Balance pill
  const totalCredit = transactions.filter((t) => t.type === "in" || t.type === "credit").reduce((s, t) => s + Number(t.amount), 0);
  const totalDebit = transactions.filter((t) => t.type === "out" || t.type === "debit").reduce((s, t) => s + Number(t.amount), 0);
  const balance = totalCredit - totalDebit;
  const isPositive = balance >= 0;

  doc.setFillColor(...(isPositive ? GREEN : RED));
  doc.roundedRect(w - 200, 100, 160, 60, 8, 8, "F");
  doc.setTextColor(220, 255, 230);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("BALANCE", w - 120, 118, { align: "center" });
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(formatMoney(Math.abs(balance)), w - 120, 144, { align: "center" });

  // Stats row
  const statY = 190;
  const statH = 56;
  const gap = 12;
  const sw = (w - 48 - gap * 2) / 3;

  const drawStat = (x: number, label: string, value: string, color: [number, number, number]) => {
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(225, 230, 240);
    doc.roundedRect(x, statY, sw, statH, 6, 6, "FD");
    doc.setFillColor(...color);
    doc.rect(x, statY, 4, statH, "F");
    doc.setTextColor(120, 130, 145);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(label, x + 14, statY + 18);
    doc.setTextColor(20, 25, 40);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(value, x + 14, statY + 40);
  };

  drawStat(24, "TOTAL CREDIT", formatMoney(totalCredit), GREEN);
  drawStat(24 + sw + gap, "TOTAL DEBIT", formatMoney(totalDebit), RED);
  drawStat(24 + (sw + gap) * 2, "TRANSACTIONS", String(transactions.length), ACCENT_BLUE);

  // Transactions table
  doc.setTextColor(...BRAND_BLUE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("TRANSACTION HISTORY", 24, 280);
  doc.setDrawColor(...ACCENT_BLUE);
  doc.setLineWidth(2);
  doc.line(24, 286, 180, 286);

  let runningBalance = 0;
  const rows = transactions
    .slice()
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
    .map((t) => {
      const isCredit = t.type === "in" || t.type === "credit";
      const amt = Number(t.amount);
      runningBalance += isCredit ? amt : -amt;
      return [
        fmtDate(t.date),
        t.type === "in" ? "Cash In" : t.type === "out" ? "Cash Out" : t.type === "credit" ? "Credit" : "Debit",
        t.category,
        t.payment_method,
        t.note || "-",
        isCredit ? formatMoney(amt) : "",
        !isCredit ? formatMoney(amt) : "",
        formatMoney(runningBalance),
      ];
    });

  autoTable(doc, {
    startY: 295,
    head: [["Date", "Type", "Category", "Method", "Notes", "Credit", "Debit", "Balance"]],
    body: rows,
    theme: "grid",
    headStyles: { fillColor: [240, 244, 250], textColor: [30, 58, 138], fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 8, textColor: [40, 50, 65] },
    alternateRowStyles: { fillColor: [250, 251, 253] },
    margin: { left: 24, right: 24, bottom: 40 },
    didParseCell: (data) => {
      if (data.section === "body") {
        if (data.column.index === 5 && data.cell.text[0]) {
          data.cell.styles.textColor = GREEN;
          data.cell.styles.fontStyle = "bold";
        }
        if (data.column.index === 6 && data.cell.text[0]) {
          data.cell.styles.textColor = RED;
          data.cell.styles.fontStyle = "bold";
        }
        if (data.column.index === 7) data.cell.styles.fontStyle = "bold";
      }
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    footer(doc, businessName);
  }

  doc.save(`statement-${customer.name.toLowerCase().replace(/\s+/g, "-")}.pdf`);
}

export function generateBusinessReport(opts: {
  businessName: string;
  transactions: PdfTx[];
  customers: PdfCustomer[];
}) {
  const { businessName, transactions } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  header(doc, businessName, "Report");

  const w = doc.internal.pageSize.getWidth();
  const cashIn = transactions.filter((t) => t.type === "in" || t.type === "credit").reduce((s, t) => s + Number(t.amount), 0);
  const cashOut = transactions.filter((t) => t.type === "out" || t.type === "debit").reduce((s, t) => s + Number(t.amount), 0);
  const net = cashIn - cashOut;

  // Summary card
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(24, 90, w - 48, 80, 8, 8, "F");
  doc.setTextColor(120, 130, 145);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("REPORT SUMMARY", 40, 110);
  doc.setTextColor(20, 25, 40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Business Financial Overview", 40, 130);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90, 100, 115);
  doc.text(`Total transactions: ${transactions.length}`, 40, 148);

  doc.setFillColor(...(net >= 0 ? GREEN : RED));
  doc.roundedRect(w - 200, 100, 160, 60, 8, 8, "F");
  doc.setTextColor(220, 255, 230);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("NET PROFIT", w - 120, 118, { align: "center" });
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(formatMoney(net), w - 120, 144, { align: "center" });

  const statY = 190;
  const statH = 56;
  const gap = 12;
  const sw = (w - 48 - gap * 2) / 3;
  const drawStat = (x: number, label: string, value: string, color: [number, number, number]) => {
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(225, 230, 240);
    doc.roundedRect(x, statY, sw, statH, 6, 6, "FD");
    doc.setFillColor(...color);
    doc.rect(x, statY, 4, statH, "F");
    doc.setTextColor(120, 130, 145);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(label, x + 14, statY + 18);
    doc.setTextColor(20, 25, 40);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(value, x + 14, statY + 40);
  };
  drawStat(24, "TOTAL CASH IN", formatMoney(cashIn), GREEN);
  drawStat(24 + sw + gap, "TOTAL CASH OUT", formatMoney(cashOut), RED);
  drawStat(24 + (sw + gap) * 2, "TRANSACTIONS", String(transactions.length), ACCENT_BLUE);

  doc.setTextColor(...BRAND_BLUE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("ALL TRANSACTIONS", 24, 280);
  doc.setDrawColor(...ACCENT_BLUE);
  doc.setLineWidth(2);
  doc.line(24, 286, 160, 286);

  const rows = transactions
    .slice()
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .map((t) => {
      const isCredit = t.type === "in" || t.type === "credit";
      const amt = Number(t.amount);
      return [
        fmtDate(t.date),
        t.type === "in" ? "Cash In" : t.type === "out" ? "Cash Out" : t.type === "credit" ? "Credit" : "Debit",
        t.category,
        t.payment_method,
        t.note || "-",
        isCredit ? formatMoney(amt) : "",
        !isCredit ? formatMoney(amt) : "",
      ];
    });

  autoTable(doc, {
    startY: 295,
    head: [["Date", "Type", "Category", "Method", "Notes", "Credit", "Debit"]],
    body: rows,
    theme: "grid",
    headStyles: { fillColor: [240, 244, 250], textColor: [30, 58, 138], fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 8, textColor: [40, 50, 65] },
    alternateRowStyles: { fillColor: [250, 251, 253] },
    margin: { left: 24, right: 24, bottom: 40 },
    didParseCell: (data) => {
      if (data.section === "body") {
        if (data.column.index === 5 && data.cell.text[0]) {
          data.cell.styles.textColor = GREEN;
          data.cell.styles.fontStyle = "bold";
        }
        if (data.column.index === 6 && data.cell.text[0]) {
          data.cell.styles.textColor = RED;
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    footer(doc, businessName);
  }

  doc.save(`business-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
