// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnqdyegcqbwezggavmvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJucWR5ZWdjcWJ3ZXpnZ2F2bXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3MDk2MjUsImV4cCI6MjA5MjI4NTYyNX0.DLplKCnWk426ysxncNay8ijd60itb4z-7NdcFN7pnZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});